/*
 * OpenWeatherMap API
 *
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: some_email@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Main : IEquatable<Main>
    { 
        /// <summary>
        /// Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
        /// </summary>
        /// <value>Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.</value>
        [DataMember(Name="temp")]
        public decimal? Temp { get; set; }

        /// <summary>
        /// Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa
        /// </summary>
        /// <value>Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa</value>
        [DataMember(Name="pressure")]
        public int? Pressure { get; set; }

        /// <summary>
        /// Humidity, %
        /// </summary>
        /// <value>Humidity, %</value>
        [DataMember(Name="humidity")]
        public int? Humidity { get; set; }

        /// <summary>
        /// Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
        /// </summary>
        /// <value>Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.</value>
        [DataMember(Name="temp_min")]
        public decimal? TempMin { get; set; }

        /// <summary>
        /// Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
        /// </summary>
        /// <value>Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.</value>
        [DataMember(Name="temp_max")]
        public decimal? TempMax { get; set; }

        /// <summary>
        /// Atmospheric pressure on the sea level, hPa
        /// </summary>
        /// <value>Atmospheric pressure on the sea level, hPa</value>
        [DataMember(Name="sea_level")]
        public decimal? SeaLevel { get; set; }

        /// <summary>
        /// Atmospheric pressure on the ground level, hPa
        /// </summary>
        /// <value>Atmospheric pressure on the ground level, hPa</value>
        [DataMember(Name="grnd_level")]
        public decimal? GrndLevel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Main {\n");
            sb.Append("  Temp: ").Append(Temp).Append("\n");
            sb.Append("  Pressure: ").Append(Pressure).Append("\n");
            sb.Append("  Humidity: ").Append(Humidity).Append("\n");
            sb.Append("  TempMin: ").Append(TempMin).Append("\n");
            sb.Append("  TempMax: ").Append(TempMax).Append("\n");
            sb.Append("  SeaLevel: ").Append(SeaLevel).Append("\n");
            sb.Append("  GrndLevel: ").Append(GrndLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Main)obj);
        }

        /// <summary>
        /// Returns true if Main instances are equal
        /// </summary>
        /// <param name="other">Instance of Main to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Main other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Temp == other.Temp ||
                    Temp != null &&
                    Temp.Equals(other.Temp)
                ) && 
                (
                    Pressure == other.Pressure ||
                    Pressure != null &&
                    Pressure.Equals(other.Pressure)
                ) && 
                (
                    Humidity == other.Humidity ||
                    Humidity != null &&
                    Humidity.Equals(other.Humidity)
                ) && 
                (
                    TempMin == other.TempMin ||
                    TempMin != null &&
                    TempMin.Equals(other.TempMin)
                ) && 
                (
                    TempMax == other.TempMax ||
                    TempMax != null &&
                    TempMax.Equals(other.TempMax)
                ) && 
                (
                    SeaLevel == other.SeaLevel ||
                    SeaLevel != null &&
                    SeaLevel.Equals(other.SeaLevel)
                ) && 
                (
                    GrndLevel == other.GrndLevel ||
                    GrndLevel != null &&
                    GrndLevel.Equals(other.GrndLevel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Temp != null)
                    hashCode = hashCode * 59 + Temp.GetHashCode();
                    if (Pressure != null)
                    hashCode = hashCode * 59 + Pressure.GetHashCode();
                    if (Humidity != null)
                    hashCode = hashCode * 59 + Humidity.GetHashCode();
                    if (TempMin != null)
                    hashCode = hashCode * 59 + TempMin.GetHashCode();
                    if (TempMax != null)
                    hashCode = hashCode * 59 + TempMax.GetHashCode();
                    if (SeaLevel != null)
                    hashCode = hashCode * 59 + SeaLevel.GetHashCode();
                    if (GrndLevel != null)
                    hashCode = hashCode * 59 + GrndLevel.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Main left, Main right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Main left, Main right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
