/*
 * OpenWeatherMap API
 *
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: some_email@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Sys : IEquatable<Sys>
    { 
        /// <summary>
        /// Internal parameter
        /// </summary>
        /// <value>Internal parameter</value>
        [DataMember(Name="type")]
        public int? Type { get; set; }

        /// <summary>
        /// Internal parameter
        /// </summary>
        /// <value>Internal parameter</value>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Internal parameter
        /// </summary>
        /// <value>Internal parameter</value>
        [DataMember(Name="message")]
        public decimal? Message { get; set; }

        /// <summary>
        /// Country code (GB, JP etc.)
        /// </summary>
        /// <value>Country code (GB, JP etc.)</value>
        [DataMember(Name="country")]
        public string Country { get; set; }

        /// <summary>
        /// Sunrise time, unix, UTC
        /// </summary>
        /// <value>Sunrise time, unix, UTC</value>
        [DataMember(Name="sunrise")]
        public int? Sunrise { get; set; }

        /// <summary>
        /// Sunset time, unix, UTC
        /// </summary>
        /// <value>Sunset time, unix, UTC</value>
        [DataMember(Name="sunset")]
        public int? Sunset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Sys {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Sunrise: ").Append(Sunrise).Append("\n");
            sb.Append("  Sunset: ").Append(Sunset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Sys)obj);
        }

        /// <summary>
        /// Returns true if Sys instances are equal
        /// </summary>
        /// <param name="other">Instance of Sys to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Sys other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    Country == other.Country ||
                    Country != null &&
                    Country.Equals(other.Country)
                ) && 
                (
                    Sunrise == other.Sunrise ||
                    Sunrise != null &&
                    Sunrise.Equals(other.Sunrise)
                ) && 
                (
                    Sunset == other.Sunset ||
                    Sunset != null &&
                    Sunset.Equals(other.Sunset)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    if (Country != null)
                    hashCode = hashCode * 59 + Country.GetHashCode();
                    if (Sunrise != null)
                    hashCode = hashCode * 59 + Sunrise.GetHashCode();
                    if (Sunset != null)
                    hashCode = hashCode * 59 + Sunset.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Sys left, Sys right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Sys left, Sys right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
